# Any of the commands may also be set interactively
# in the shell with `tmux ...` or within tmux with `<Ctrl-b>:`

# https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-a-256-colour-terminal
# Also ensure in .vimrc: set t_Co=256 " Enable 256 color support in terminal
set-option -g default-terminal "screen-256color"

# Avoid delay when pressing Escape key in VIM
# See also: :help timeout in VIM
# See also: https://superuser.com/questions/942677/consequences-of-escape-time-0-tmux-setting
set-option -g escape-time 100

set-option -g wrap-search off
set-option -g base-index 1 # Start counting windows at 1
set-option -g renumber-windows on # Fill empty slots left by closed windows
set-option -g history-limit 100000 # Save more lines of scrollback
set-window-option -g mode-keys vi # Use VIM inspired navigation in copy-mode
set-window-option -g pane-base-index 1 # Start counting panes at 1

# Navigate panes and windows without a prefix
bind-key -n M-Up select-pane -U
bind-key -n M-Left select-pane -L
bind-key -n M-Down select-pane -D
bind-key -n M-Right select-pane -R
bind-key -n M-1 select-window -t :=1
bind-key -n M-2 select-window -t :=2
bind-key -n M-3 select-window -t :=3
bind-key -n M-4 select-window -t :=4
bind-key -n M-5 select-window -t :=5
bind-key -n M-6 select-window -t :=6
bind-key -n M-7 select-window -t :=7
bind-key -n M-8 select-window -t :=8
bind-key -n M-9 select-window -t :=9

# Create new panes from current directory
bind-key -T prefix % split-window -h -c "#{pane_current_path}"
bind-key -T prefix '"' split-window -v -c "#{pane_current_path}"

# Be more like vim terminals in copy-mode-vi and search incrementally
bind-key -T copy-mode-vi a send-keys -X cancel
bind-key -T copy-mode-vi i send-keys -X cancel
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi C-V send-keys -X rectangle-toggle
bind-key -T copy-mode-vi / command-prompt -i -p "(search down)" "send-keys -X search-forward-incremental \"%%%\""
bind-key -T copy-mode-vi ? command-prompt -i -p "(search up)" "send-keys -X search-backward-incremental \"%%%\""

# Allow directly entering search mode from terminal mode
# Requires rebinding ? which shows help to h which is unused
bind-key -T prefix / command-prompt -i -p "(search down)" "send-keys -X search-forward-incremental \"%%%\""
bind-key -T prefix ? command-prompt -i -p "(search up)" "send-keys -X search-backward-incremental \"%%%\""
bind-key -T prefix h list-keys
